# Generated by Django 5.1.4 on 2024-12-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_title_not_empty'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='title_not_empty',
        ),
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.ImageField(default='network/no-image.png', upload_to='network/'),
        ),
    ]
