# Generated by Django 5.1.4 on 2024-12-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_username_postlike_user_postarchive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ManyToManyField(related_name='post_commented', to='network.post'),
        ),
    ]
